In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pdb
from IPython.display import display
import os
import seaborn as sns
import statsmodels.formula.api as sm
from numpy.polynomial.polynomial import polyfit
from sklearn.model_selection import train_test_split
import sklearn
from math import sqrt
import glob

In [11]:
s_patens = pd.read_csv('C:/Users/arj26323/Documents/Data/Biomass datasets/Massachusetts/LTE-MP-LPP-biomass.csv')
s_alterniflora = pd.read_csv('C:/Users/arj26323/Documents/Data/Biomass datasets/Massachusetts/LTE-MP-LPA-biomass.csv')

s_patens['Latitude'] = 42.730953216553
s_patens['Longitude'] = -70.842918395996

s_alterniflora['Latitude'] = 42.730954
s_alterniflora['Longitude'] = -70.842915

s_patens.rename(columns={'LIVE biomass':'liveMass'}, inplace=True)
s_alterniflora.rename(columns={'MEAN BIOMASS':'liveMass'}, inplace=True)

df = pd.concat([s_patens, s_alterniflora])

display(df)

,SITE,YEAR,MONTH,DAY,PLOT,TRT,SP biomass,DS biomass,SA biomass,SE biomass,liveMass,DEAD biomass,Latitude,Longitude,BIOMASS SE,MEAN PLANT DENSITY,DENSITY SE
0,LTE-MP-LPP,2000,8,24,1,N,756.0,0.0,68.0,0.0,823.0,497,42.730953,-70.842918,NaN,NaN,NaN
1,LTE-MP-LPP,2000,8,24,2,P,313.0,0.0,0.0,0.0,313.0,248,42.730953,-70.842918,NaN,NaN,NaN
2,LTE-MP-LPP,2000,8,24,3,N,406.0,0.0,0.0,0.0,406.0,294,42.730953,-70.842918,NaN,NaN,NaN
3,LTE-MP-LPP,2000,8,24,4,N,403.0,0.0,0.0,0.0,403.0,261,42.730953,-70.842918,NaN,NaN,NaN
4,LTE-MP-LPP,2000,8,24,6,P,725.0,0.0,0.0,0.0,725.0,297,42.730953,-70.842918,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,LTE-MP-LPA,2018,5,2,NaN,NP,NaN,NaN,NaN,NaN,25.5,NaN,42.730954,-70.842915,4.5,2050.0,250.0
220,LTE-MP-LPA,2018,6,8,NaN,NP,NaN,NaN,NaN,NaN,792.7,NaN,42.730954,-70.842915,194.5,2600.0,355.9
221,LTE-MP-LPA,2018,7,18,NaN,NP,NaN,NaN,NaN,NaN,1163.7,NaN,42.730954,-70.842915,212.4,2333.3,197.8
222,LTE-MP-LPA,2018,8,28,NaN,NP,NaN,NaN,NaN,NaN,636.8,NaN,42.730954,-70.842915,121.9,3050.0,368.6
223,LTE-MP-LPA,2018,10,3,NaN,NP,NaN,NaN,NaN,NaN,361.2,NaN,42.730954,-70.842915,53.6,3050.0,378.4