In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pdb
from IPython.display import display
import os
import seaborn as sns
import statsmodels.formula.api as sm
from numpy.polynomial.polynomial import polyfit
from sklearn.model_selection import train_test_split
import sklearn
from math import sqrt
import glob

In [3]:
import ee
import geemap
service_account = ' boba-account@boba-430314.iam.gserviceaccount.com '
credentials = ee.ServiceAccountCredentials(service_account,'C:/Users/arj26323/OneDrive - University of Georgia/Documents/GEE AUTH/boba-430314-a19be859bfca.json')

ee.Initialize(credentials)

print(geemap.__version__)

0.34.1

In [4]:
##Remote sensing data:
import glob

path = r'C:/Users/arj26323//Documents/All extract/GAVA_combined'

all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df1 = pd.read_csv(filename, index_col=None, header=0)
    li.append(df1)

df1 = pd.concat(li, axis=0, ignore_index=True)

df1

display(df1)

# for col in df1.columns:
#     print(col)

,Latitude,Longitude,Plant_Biomass,QA_PIXEL,QA_RADSAT,SR_ATMOS_OPACITY,SR_B1,SR_B2,SR_B3,SR_B4,...,ST_TRAD,ST_URAD,Site,Year,date,flats,index,SR_B6,SR_QA_AEROSOL,ST_B10
0,31.308449,-81.415129,440.816,5440,0,319.0,0.032183,0.05025,0.04024,0.176805,...,8769,3161,GA,2013,1984-05-14,0.000630,0,NaN,NaN,NaN
1,31.308449,-81.415129,468.640,5440,0,319.0,0.032183,0.05025,0.04024,0.176805,...,8769,3161,GA,2015,1984-05-14,0.000630,1,NaN,NaN,NaN
2,31.308449,-81.415129,170.976,5440,0,319.0,0.032183,0.05025,0.04024,0.176805,...,8769,3161,GA,2016,1984-05-14,0.000630,2,NaN,NaN,NaN
3,31.308449,-81.415129,140.192,5440,0,319.0,0.032183,0.05025,0.04024,0.176805,...,8769,3161,GA,2018,1984-05-14,0.000630,3,NaN,NaN,NaN
4,31.308449,-81.415129,435.200,5440,0,319.0,0.032183,0.05025,0.04024,0.176805,...,8769,3161,GA,2021,1984-05-14,0.000630,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1778649,31.351196,-81.333574,340.736,21824,0,NaN,0.025747,0.02847,0.03705,0.038837,...,7352,574,GA,2004,2024-12-21,0.001119,625,0.106102,96.0,285.266203
1778650,31.351196,-81.333574,695.056,21824,0,NaN,0.025747,0.02847,0.03705,0.038837,...,7352,574,GA,2005,2024-12-21,0.001119,626,0.106102,96.0,285.266203
1778651,31.351196,-81.333574,575.312,21824,0,NaN,0.025747,0.02847,0.03705,0.038837,...,7352,574,GA,2006,2024-12-21,0.001119,627,0.106102,96.0,285.266203
1778652,31.351196,-81.333574,374.208,21824,0,NaN,0.025747,0.02847,0.03705,0.038837,...,7352,574,GA,2020,2024-12-21,0.001119,628,0.106102,96.0,285.266203
1778653,31.351197,-81.333752,385.616,21824,0,NaN,0.025747,0.02847,0.03705,0.038837,...,7352,574,GA,2000,2024-12-21,0.001119,629,0.106102,96.0,285.266203

In [6]:
##No way to remove sites 8 and 9 without Zone/Transect info

In [9]:
#Distinguishing between sensors, in order to make indices: USE PRESENCE OF DATA IN B10

df1['Sensor'] = np.where(df1['ST_B10'].isna(),'Landsat 5/7', 'Landsat 8/9')

df1['Date'] = pd.to_datetime(df1['Year'])

#Datetime and year for LS data and biomass sampling data
df1['LS_datetime'] = pd.to_datetime(df1['date'], format='%Y-%m-%d')
df1['LS_year'] = df1['LS_datetime'].dt.strftime('%Y')

df1['Sampling_datetime'] = pd.to_datetime(df1['Date'])
df1['Sampling_year'] = df1['Sampling_datetime'].dt.strftime('%Y')

df1['Month'] = df1['LS_datetime'].dt.month #IMPORTANT FOR VARIABLES! MUST BE SAMPLING LS TIME

# df1[df1['Sensor'] == 'Landsat 5/7'] #652450 5/7, 1126204 8/9

# df1['Month']

In [14]:
#Renaming bands, based on Landsat sensors

df1['Blue_band'] = np.where(df1['Sensor'] == 'Landsat 8/9', df1['SR_B2'], df1['SR_B1'])
df1['Green_band'] = np.where(df1['Sensor'] == 'Landsat 8/9', df1['SR_B3'], df1['SR_B2'])
df1['Red_band'] = np.where(df1['Sensor'] == 'Landsat 8/9', df1['SR_B4'], df1['SR_B3'])
df1['NIR_band'] = np.where(df1['Sensor'] == 'Landsat 8/9', df1['SR_B5'], df1['SR_B4'])
df1['SWIR1_band'] = np.where(df1['Sensor'] == 'Landsat 8/9', df1['SR_B6'], df1['SR_B5'])
df1['SWIR2_band'] = np.where(df1['Sensor'] == 'Landsat 8/9', df1['SR_B7'], df1['SR_B7'])

#THERMAL BANDS
df1['thermal_band_kelvin'] = np.where(df1['Sensor'] == 'Landsat 8/9', df1['ST_B10'], df1['ST_B6'])
df1['thermal_band_celsius'] = df1['thermal_band_kelvin'] - 273.15

##Indices (make sure calculations are accurate):
df1['savi'] = ((df1['NIR_band']-df1['Red_band'])*1.5)/(df1['NIR_band']+df1['Red_band']+0.5)
df1['wdrvi5'] = (0.5*df1['NIR_band']-df1['Red_band'])/(0.5*df1['NIR_band']+df1['Red_band'])
df1['nd_r_g'] = (df1['Red_band']-df1['Green_band'])/(df1['Red_band']+df1['Green_band'])
df1['nd_g_b'] = (df1['Green_band']-df1['Blue_band'])/(df1['Green_band']+df1['Blue_band'])
df1['nd_swir2_nir'] = (df1['SWIR2_band']-df1['NIR_band'])/(df1['SWIR2_band']+df1['NIR_band'])
df1['nd_swir2_r'] = (df1['SWIR2_band']-df1['Red_band'])/(df1['SWIR2_band']+df1['Red_band'])
df1['evi'] =((df1['NIR_band']-df1['Red_band'])*2.5)/(df1['NIR_band']+6*df1['Red_band']+7.5*df1['Blue_band']+1)
df1['ndvi'] = ((df1['NIR_band']-df1['Red_band']))/(df1['NIR_band']+df1['Red_band'])

In [15]:
# df1['date'] is the Landsat extraction date, ranging from 1985-2024! df1['Date'] is the sampling date for each site! (2000-2?)
#df1['Year'] is the sampling year as well! Starting in 2000
# # df1['Year']
# for col in df1.columns:
#     print(col)

# df1['thermal_band_celcius']

In [18]:
# pairsite = df1[['Latitude', 'Longitude', 'Site']].drop_duplicates()
# pairsite

In [19]:
##ADDITIONAL GROUP BY LS YEAR

def seasonal_band_stats(df, start_month, end_month, bands, stat_name='mean'):
    # Filter by month range
    df_season = df[(df['Month'] >= start_month) & (df['Month'] <= end_month)]
    
    # Filter to only those rows where LS_year matches Sampling_year
    df_season = df_season[df_season['LS_year'] == df_season['Sampling_year']]

    # Grouping by location and both year types
    group_cols = ['Latitude', 'Longitude', 'Sampling_year', 'LS_year']  ##ADD SITE???????
    
    # Choose aggregation function
    if stat_name == 'mean':
        agg_func = 'mean'
    elif stat_name == 'min':
        agg_func = 'min'
    elif stat_name == 'max':
        agg_func = 'max'
    elif stat_name == 'median':
        agg_func = 'median'
    elif stat_name == 'sum':
        agg_func = 'sum'    
    else:
        raise ValueError("stat_name must be 'mean', 'min', 'max', 'sum,' or 'median'")
    
    # Perform aggregation
    df_grouped = df_season.groupby(group_cols)[bands].agg(agg_func).reset_index()
    
    # Rename columns to reflect the operation and month window
    suffix = f'{stat_name}_{start_month:02d}_{end_month:02d}'
    df_grouped = df_grouped.rename(columns={col: f'{col}_{suffix}' for col in bands})
    
    return df_grouped

In [20]:
##Flooding dataset                                              )

df1_flooding = df1.groupby(['Latitude', 'Longitude', 'Plant_Biomass','Sampling_year']).apply(
    lambda g: (g['flats'] >= 0.2).mean()).reset_index(name='Percent_flooding'
                                                     )
##DO NOT GROUP FLOODING PERCENT BY LS_YEAR - you want the total percent flooding over the entire time period. ADD AT END?

df1_flooding

       Latitude  Longitude  Plant_Biomass Sampling_year  Percent_flooding
0     31.308449 -81.415129         71.520          1970          0.014085
1     31.308449 -81.415129        140.192          1970          0.014085
2     31.308449 -81.415129        161.872          1970          0.014085
3     31.308449 -81.415129        170.976          1970          0.014085
4     31.308449 -81.415129        250.240          1970          0.014085
...         ...        ...            ...           ...               ...
4038  37.482109 -75.818885        226.400          1970          0.050000
4039  37.482109 -75.818885        771.200          1970          0.050000
4040  37.482293 -75.819265        104.000          1970          0.133080
4041  37.482293 -75.819265        156.000          1970          0.133080
4042  37.482293 -75.819265       1108.800          1970          0.133080

[4043 rows x 5 columns]